name: 'lakehouse_utils'
version: '1.0.0'
config-version: 2
require-dbt-version: ">=1.0.0"
profile: 'lakehouse'

model-paths: ["tmp/snow"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

