version: 2.1


name: Circle
on:
  pull_request:
    branches:
    - main

jobs:
  build:
    docker:
      - image: cimg/python:3.9.9
      
       

    steps:
      - checkout

      

      - run:
          name: "Setup dbt"
          command: | 
            set -x

            python -m venv dbt_venv
            . dbt_venv/bin/activate

            python -m pip install --upgrade pip setuptools
            python -m pip install dbt-databricks==1.5.5
            pwd
            python3 helper/convert_to_databricks.py --sourcedb "redshift" --dir_path "redshift/" --parse_mode 'syntax' --parse_first 'syntax' 
            python3 helper/convert_to_databricks.py --sourcedb "redshift" --dir_path "/Workspace/Repos/roberto.salcido@databricks.com/lakehouse_utils/beyondsqltest/testpyfiles" --parse_mode 'syntax' --parse_first 'syntax' --dir_mode 'nondbt' --file_type 'py' --except_list 'uno.py','dos.py'
            python3 helper/convert_to_databricks.py --sourcedb "redshift" --dir_path "/Workspace/Repos/roberto.salcido@databricks.com/lakehouse_utils/beyondsqltest/testlookmlfiles" --parse_mode 'syntax' --parse_first 'syntax' --dir_mode 'lookml' --file_type 'lkml' --except_list 'dos.lkml','tres.lkml'
            python3 integration_tests/regexit.py
            
      - store_artifacts:
          path: integration_tests/logs
      - store_artifacts:
          path: integration_tests/target

workflows:
  
  test-all:
    jobs:
      - build:
          context:
            - profile-databricks
