version: 2.1


name: Circle
on:
  pull_request:
    branches:
    - main

jobs:
  build:
    docker:
      - image: cimg/python:3.9.9
      
       

    steps:
      - checkout

      

      - run:
          name: "Setup dbt"
          command: | 
            set -x

            python -m venv dbt_venv
            . dbt_venv/bin/activate

            python -m pip install --upgrade pip setuptools
            python -m pip install dbt-databricks==1.5.5

            

            
      - store_artifacts:
          path: integration_tests/logs
      - store_artifacts:
          path: integration_tests/target

workflows:
  
  test-all:
    jobs:
      - build:
          context:
            - profile-databricks
