integration_tests:
  target: databricks

  outputs:

    snow:
      type: snowflake
      account: accounthere

      # User/password auth
      user: userhere
      password: pwhere
      
      role: rolehere
      database: dbhere
      warehouse: warehousehere
      schema: schemahere
      threads: 1
      client_session_keep_alive: False

    databricks:
      type: databricks
      method: http
      catalog: hive_metastore
      schema: robertocircle
      host: e2-dogfood.staging.cloud.databricks.com

      token: "{{ env_var('dbtokendf') }}"
      http_path: /sql/1.0/warehouses/1cef66d7b4e17fe9 
