integration_tests:
  target: databricks

  outputs:

    snowflake:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_TEST_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_TEST_USER') }}"
      password: "{{ env_var('SNOWFLAKE_TEST_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_TEST_ROLE') }}"
      database: "{{ env_var('SNOWFLAKE_TEST_DATABASE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_TEST_WAREHOUSE') }}"
      schema: "{{ env_var('SNOWFLAKE_TEST_SCHEMA') }}"


    databricks:
      type: databricks
      method: http
      catalog: "{{ env_var('DATABRICKS_TEST_CATALOG') }}"
      schema: "{{ env_var('DATABRICKS_TEST_SCHEMA') }}"
      host: "{{ env_var('DATABRICKS_TEST_HOST') }}"

      token: "{{ env_var('DATABRICKS_TEST_TOKEN') }}"
      http_path: "{{ env_var('DATABRICKS_TEST_PATH') }}"
