integration_tests:
  target: databricks

  outputs:

    snow:
      type: snowflake
      account: accounthere

      # User/password auth
      user: userhere
      password: pwhere
      
      role: rolehere
      database: dbhere
      warehouse: warehousehere
      schema: schemahere
      threads: 1
      client_session_keep_alive: False

    databricks:
      type: databricks
      method: http
      catalog: "{{ env_var('DATABRICKS_TEST_CATALOG') }}"
      schema: "{{ env_var('DATABRICKS_TEST_SCHEMA') }}"
      host: "{{ env_var('DATABRICKS_TEST_HOST') }}"

      token: "{{ env_var('DATABRICKS_TEST_TOKEN') }}"
      http_path: "{{ env_var('DATABRICKS_TEST_PATH') }}"
