
name: main
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: abc
        id: def
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}

